
class BlogEditor:
    def __init__(self):
        pass

    def edit(self, draft_md):
        # Very simple editing: ensure heading levels and strip trailing spaces
        lines = [ln.rstrip() for ln in draft_md.splitlines()]
        # Example change: append a short conclusion paragraph if missing
        if 'Conclusion' not in draft_md and lines:
            lines.append('\n## Conclusion\nThis post was auto-generated by the blogger_agent system.')
        return '\n'.join(lines)
